# QI Configuration file, see: https://github.com/amatas/vagrant-gpii-ci
---

env:
  vms:
    windows10:
      cpu: 2                   # number of cpus
      memory: 2048             # amount of RAM memory (in Mb)
      clone: true              # use the linked_clone Vagrant feature
      autostart: true
      box: inclusivedesign/windows10-eval-x64-Apps

stages:                # Stages to perform when 'ci test' command is invoked
  - setup              # Install our system-level dependencies, etc.
#  - clone              # Clone our working repo to a local filesystem.
  - test               # Run the actual tests

setup_job:
  stage: setup
  script:
    - choco upgrade firefox -y
    - choco install nodejs.install --version 6.9.1 --forcex86 -y
    - do.ps1 -c "npm install -g rimraf node-inspector"
    - do.ps1 -c "npm config set bin-links false --global"
    - "net use v: \\\\vboxsrv\\vagrant  /yes"
    - "do.ps1 -c 'net use v: \\\\VBOXSVR\\vagrant /yes'"

clone_job:
  stage: clone
  script:
    - "rimraf c:/users/vagrant/diff"
    - "rimraf c:/users/vagrant/cloned"
    - "v:; git config core.safecrlf false"
    # TODO: Review with the team.  This works from the shell, but results in an unusable patch when run here.  Likely down to the difference between do.ps1 and not.
    - "v:; git diff > c:/users/vagrant/diff"
    - "v:; git clone -q v:/ c:/users/vagrant/cloned"
    - "cd c:/users/vagrant/cloned; git apply ../diff"

test_job:
  stage: test          # name of the stage
  script:              # One line per command to execute
    - "do.ps1 -c 'v: && npm install && npm test'"
